name: Delete all workflow runs

on:
  push:
    branches:
      - main

jobs:
  delete-workflow-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            github.rest.actions.deleteWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo
            })
